[Service]
Environment=OPENAI_API_KEY=sk_958db26ebcf8351fe5865d1f7faf0c82
Environment=INCEPTION_API_KEY=sk_958db26ebcf8351fe5865d1f7faf0c82
Environment=API_BASE=https://api.inceptionlabs.ai/v1
Environment=MODEL=mercury-2
Environment=ELEVEN_LABS_API=sk_255591c831811ba6d39e402ccaad6ffecee2046f3acaf706
Environment=TELEGRAM_BOT_TOKEN=8334090984:AAELS-YOMeZ72SaIPp79zl_YcVCjJxDqGhY
