const http = require("http");
const fs = require("fs");
const path = require("path");
const AGENT_NAME = process.env.AGENT_NAME || "Cosmos";
const AGENT_ROLE = process.env.AGENT_ROLE || "Engineering Lead";
const PORT = parseInt(process.env.AGENT_PORT || "4717", 10);
const API_KEY = process.env.OPENAI_API_KEY || process.env.INCEPTION_API_KEY || process.env.MERCURY2_API_TOKEN || process.env.MERCURY_API_KEY || "";
const API_BASE = (process.env.API_BASE || "https://api.inceptionlabs.ai/v1").replace(/\/$/, "");
const MODEL = process.env.MODEL || "mercury-2";
const PAULI_ROOT = process.env.PAULI_ROOT || "/opt/pauli-effect";
const REASONING = process.env.MERCURY_REASONING || "";
const MAX_TOKENS = parseInt(process.env.MAX_TOKENS || "1200", 10);
const startTime = Date.now();
let currentMission = null;
const missionHistory = [];
const logs = [];
function log(msg){const e="["+new Date().toISOString()+"] "+msg; logs.push(e); if(logs.length>200) logs.shift(); console.log(e);}
function readSafe(p,max=12000){try{if(!fs.existsSync(p)) return ""; return fs.readFileSync(p,"utf8").slice(0,max);}catch(e){return "";}}
function loadIcm(){const parts=[readSafe(path.join(PAULI_ROOT,"AGENTS.md"),4000),readSafe(path.join(PAULI_ROOT,"CONTEXT.md"),4000),readSafe(path.join(PAULI_ROOT,"agents/cosmos-pi/CONTEXT.md"),4000),readSafe(path.join(PAULI_ROOT,"guardrails/HARD_BLOCKS.md"),2500)]; try{const s=path.join(PAULI_ROOT,"library/shelves"); if(fs.existsSync(s)) parts.push("Library shelves: "+fs.readdirSync(s).join(", "));}catch(e){} return parts.filter(Boolean).join("\n\n---\n\n");}
function systemContext(){return "You are "+AGENT_NAME+", the "+AGENT_ROLE+" of The Pauli Effect.\nDirector: Bambu. Partners: Hermes, TARS, Cosmos-II.\nRules: no emojis in code; technical prose; direct; anti-slop; ICM folder tree is orchestration.\nOn mission: restate, plan 3-6 bullets, risks, first next action.\nBrain: "+MODEL+" via "+API_BASE+".\n\nICM:\n"+loadIcm();}
async function think(userMessage){if(!API_KEY) return "["+AGENT_NAME+" demo] "+userMessage; const body={model:MODEL,messages:[{role:"system",content:systemContext()},{role:"user",content:userMessage}],max_tokens:MAX_TOKENS,temperature:0.4,...(REASONING ? {reasoning_effort:REASONING} : {})}; const resp=await fetch(API_BASE+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+API_KEY},body:JSON.stringify(body)}); const data=await resp.json(); if(!resp.ok) return "[model error "+resp.status+"] "+JSON.stringify(data).slice(0,400); return (data.choices&&data.choices[0]&&data.choices[0].message&&data.choices[0].message.content)||"[No response]";}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,"http://localhost:"+PORT); const json=(c,d)=>{res.writeHead(c,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*"}); res.end(JSON.stringify(d,null,2));}; const readBody=()=>new Promise(r=>{let b=""; req.on("data",x=>b+=x); req.on("end",()=>r(b));}); if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization"}); return res.end();} if(url.pathname==="/health") return json(200,{status:"ok",agent:AGENT_NAME,role:AGENT_ROLE,runtime:"cosmos-pi-mercury",uptime:Math.floor((Date.now()-startTime)/1000),current_mission:currentMission?currentMission.mission:null,model:API_KEY?MODEL:"demo-mode",api_base:API_BASE}); if(url.pathname==="/status") return json(200,{agent:AGENT_NAME,role:AGENT_ROLE,online:true,runtime:"cosmos-pi-mercury",uptime:Math.floor((Date.now()-startTime)/1000),missions_completed:missionHistory.length,current_mission:currentMission,recent_logs:logs.slice(-8),model:MODEL}); if(url.pathname==="/mission"&&req.method==="POST"){try{const mission=JSON.parse(await readBody()); currentMission=mission; log("Mission: "+String(mission.mission||"").slice(0,120)); const response=await think("Mission: "+mission.mission+"\nContext: "+(mission.context||"none")+"\nPriority: "+(mission.priority||"normal")); mission.result=response; mission.completed_at=new Date().toISOString(); missionHistory.push(mission); currentMission=null; return json(200,{accepted:true,response,model:MODEL,runtime:"cosmos-pi-mercury"});}catch(err){log("Mission error: "+err.message); return json(400,{error:err.message});}} if(url.pathname==="/chat"&&req.method==="POST"){try{const payload=JSON.parse(await readBody()); const message=payload.message||payload.question||""; if(!message) return json(400,{error:"empty message"}); const response=await think(message); return json(200,{response,model:MODEL});}catch(err){return json(400,{error:err.message});}} if(url.pathname==="/logs") return json(200,logs); if(url.pathname==="/"||url.pathname==="/index.html"){res.writeHead(200,{"Content-Type":"text/html"}); return res.end("<html><body style=\"font-family:system-ui;background:#111;color:#eee;padding:24px\"><h1 style=\"color:#F5A617\">"+AGENT_NAME+"</h1><p>"+AGENT_ROLE+" · Mercury-2 · "+PORT+"</p><p>/health /mission /chat /status</p></body></html>");} return json(404,{error:"Not found"});});
server.listen(PORT,"0.0.0.0",()=>log(AGENT_NAME+" runtime=cosmos-pi-mercury port="+PORT+" model="+MODEL));
